spring:
  application:
    name: SkillSync-AI
  datasource:
    url: jdbc:postgresql://localhost:5432/skillsync
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: qwen/qwen3-coder:free
          temperature: 0.7
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        initialize-schema: true

server:
  port: 9090
