spring:
  application:
    name: SkillSync-AI
  datasource:
    url: jdbc:postgresql://localhost:5454/vectordb?options=-c%20TimeZone=UTC
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: qwen/qwen3-coder:free
          temperature: 0.7

server:
  port: 9090
