spring:
  application:
    name: SkillSync-AI
  datasource:
    url: jdbc:postgresql://localhost:5454/vectordb?TimeZone=Asia/Kolkata
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect   
  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: arcee-ai/trinity-mini:free
          temperature: 0.7
    # google:
    #   genai:
    #     api-key: AIzaSyDZ0MLb0yin9wbR2b7-ZKJ348BWYaLpKL4
    #     chat:
    #       options:
    #         model: gemini-2.0-flash-exp
    #         temperature: 0.7
    #     embedding:
    #       options:
    #         model: text-embedding-004

server:
  port: 9090
